// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-ys_Dtp8chP6gMFcywHtLSBirr6-jjo',
    appId: '1:95219328050:web:9b0936bdbd7eb3d31a482b',
    messagingSenderId: '95219328050',
    projectId: 'keko-587c3',
    authDomain: 'keko-587c3.firebaseapp.com',
    storageBucket: 'keko-587c3.firebasestorage.app',
    measurementId: 'G-ZS6F677Q29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgJ4E3_J9wPcvtdX9fslr3P7HztCo3Y1g',
    appId: '1:95219328050:android:eb60ec84672432941a482b',
    messagingSenderId: '95219328050',
    projectId: 'keko-587c3',
    storageBucket: 'keko-587c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWOEG-LXyuStWsGbNLblJbVtRK7Viwzxc',
    appId: '1:95219328050:ios:300ef8427ae244851a482b',
    messagingSenderId: '95219328050',
    projectId: 'keko-587c3',
    storageBucket: 'keko-587c3.firebasestorage.app',
    iosBundleId: 'com.example.coffeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWOEG-LXyuStWsGbNLblJbVtRK7Viwzxc',
    appId: '1:95219328050:ios:300ef8427ae244851a482b',
    messagingSenderId: '95219328050',
    projectId: 'keko-587c3',
    storageBucket: 'keko-587c3.firebasestorage.app',
    iosBundleId: 'com.example.coffeShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG-ys_Dtp8chP6gMFcywHtLSBirr6-jjo',
    appId: '1:95219328050:web:5e588bc4c9f0a6cb1a482b',
    messagingSenderId: '95219328050',
    projectId: 'keko-587c3',
    authDomain: 'keko-587c3.firebaseapp.com',
    storageBucket: 'keko-587c3.firebasestorage.app',
    measurementId: 'G-W8SKNHFQMN',
  );
}
